name: Deploy to Web Server

on:
  pull_request:
    branches:
      - ${{ vars.WEB_LANDING_DEPLOY_BRANCH }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.WEB_LANDING_KEY }}

      - name: Add SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ vars.WEB_LANDING_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy files
        run: |
          rsync -avz --delete ${{ vars.WEB_LANDING_LOCAL_PATH }} ${{ secrets.WEB_LANDING_USERNAME }}@${{ vars.WEB_LANDING_HOST }}:${{ vars.WEB_LANDING_FTP_PATH }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.WEB_LANDING_KEY }}
