name: CI Pipeline

on:
  pull_request:
    branches:
      - dev

jobs:

  build:
    runs-on: ${{ vars.RUNNER_DISTRIBUTION}}
    defaults:
      run:
        working-directory: ${{ vars.SLN_PATH }}
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ vars.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Archive build output
      uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: ${{ vars.SLN_PATH }}  

  test:
    runs-on: ${{ vars.RUNNER_DISTRIBUTION}}
    needs: build

    steps:

    - name: get build output
      uses: actions/download-artifact@v2
      with:
        name: build-output  

    - name: Execute tests 
      run: dotnet test

